import type { Metadata, Viewport } from 'next';
import { Montserrat } from 'next/font/google';

import { Header } from '@/components/Header';
import { cn } from '@/lib/utils';
import { Footer } from '@/components/Footer';

import './globals.css';
const montserrat = Montserrat({ subsets: ['latin'], weight: ['600'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const viewport: Viewport = {
	themeColor: '#171717',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn('bg-neutral-900', montserrat.className)}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
