import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { cn } from '@/lib/utils';

const montserrat = Montserrat({ subsets: ['latin'], weight: ['600'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn('bg-gradient-to-b from-neutral-900 to-neutral-800', montserrat.className)}>
				<Header />
				{children}
			</body>
		</html>
	);
}
